# Generated by Django 5.2.5 on 2025-08-31 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cigarros',
            new_name='Cigarro',
        ),
    ]
