# Generated by Django 5.2.5 on 2025-09-16 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0002_rename_cigarros_cigarro'),
    ]

    operations = [
        migrations.AddField(
            model_name='cigarro',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='cigarros'),
        ),
    ]
